### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pastle** [g1257/dmrgpp#36]
Hi,

I'm trying to install dmrgpp on ubuntu following the tutorial.
In the final step of make in the dmrgpp/src folder, there are errors related to 'KronUtil/libkronutil.a':

```
> g++ -frecord-gcc-switches -pedantic -std=c++11 -Wall -Wendif-labels -I/usr/include/hdf5/serial -DUSE_BOOST -DUSE_PTHREADS -O3 -DNDEBUG -I ../../PsimagLite -I ../../PsimagLite/src -I Engine  -c manyOmegas.cpp
> ar rcs libdmrgpp.a Provenance.o ProgramGlobals.o Qn.o Utils.o
> make: *** No rule to make target 'KronUtil/libkronutil.a', needed by 'manyOmegas'.  Stop.
```

What might be the problems?

Wishes
Shang

**Comment by g1257** [comment]
Make sure you run

cd dmrgpp/src
./configure.pl
which creates the Makefile.

If the problem persists, would you please provide the Makefile.

Thanks.

**Comment by pastle** [comment]
Thank you for your reply.
I did run the './configure.pl' command before 'make', and the installation looks fine before hitting the 'manyOmegas' section.

My Makefile is attached.
[Makefile.txt](https://github.com/g1257/dmrgpp/files/5138712/Makefile.txt)

**Comment by g1257** [comment]
On 8/27/20 4:43 PM, Shang Gao wrote:
> Thank you for your reply.
> I did run the './configure.pl' command before 'make', and the installation looks fine before hitting the 'manyOmegas' section.
> 
> My Makefile is attached.
> [Makefile.txt](https://github.com/g1257/dmrgpp/files/5138712/Makefile.txt)
> 
> 
> 

Please try the following

make dmrgpp observe operator -j 4

You can adjust 4 to the number of cores you want to use for compilation.


This won't make manyOmegas or procOmegas.

If you want to make those then you need to edit the Makefile and change
where it says
manyOmegas: manyOmegas.o libdmrgpp.a KronUtil/libkronutil.a
into
manyOmegas: manyOmegas.o libdmrgpp.a libkronutil.a

and similar for procOmegas. I will fix this in the next round next month.

Please let me know of any other problems. Thanks.

**Comment by pastle** [comment]
> If you want to make those then you need to edit the Makefile and change
> where it says
> manyOmegas: manyOmegas.o libdmrgpp.a KronUtil/libkronutil.a
> into
> manyOmegas: manyOmegas.o libdmrgpp.a libkronutil.a
> and similar for procOmegas. I will fix this in the next round next month.

Changing the Makefile as you suggested fixes the problem. Now dmrgpp is installed successfully and the test looks fine. Thanks a lot!
