### ISSUE TITLE
manual.tex is not generated

### ISSUE THREAD

**Issue by pastle** [g1257/dmrgpp#37]
The manual.tex file is not generated in the installation. When manually running the following command as in the MakeFile:
>'find ../src -iname "*.h" -or -iname "*.cpp" | ../../PsimagLite/scripts/doc.pl manual.ptex'

There is an error message:

> '../../PsimagLite/scripts/doc.pl: ERROR: Label DmrgDriver is duplicate'

What might be the problem?

**Comment by g1257** [comment]
On 9/18/20 3:53 PM, Shang Gao wrote:
> The manual.tex file is not generated in the installation. When manually running the following command as in the MakeFile:
>> 'find ../src -iname "*.h" -or -iname "*.cpp" | ../../PsimagLite/scripts/doc.pl manual.ptex'
> 
> There is an error message:
> 
>> '../../PsimagLite/scripts/doc.pl: ERROR: Label DmrgDriver is duplicate'
> 
> What might be the problem?
> 
> 
> 

This has already been corrected in the features version,
and will be pushed to Github when we update the master version.

In the meantime, you can do
cd dmrgpp/
git pull https://code.ornl.gov/gonzalo_3/dmrgpp.git  features

See also https://g1257.github.io/availabilityOfSoftware.html

**Comment by pastle** [comment]
It works now. Thanks a lot!
